"""empty message

Revision ID: 13eba2427714
Revises: 313f88b34eab
Create Date: 2020-07-24 07:57:54.043487

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13eba2427714'
down_revision = '313f88b34eab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shows', sa.Column('start_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shows', 'start_time')
    # ### end Alembic commands ###
