"""empty message

Revision ID: 313f88b34eab
Revises: be6ad7c23c58
Create Date: 2020-07-23 22:28:07.112519

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '313f88b34eab'
down_revision = 'be6ad7c23c58'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('seeking_description', sa.String(length=500), nullable=True))
    op.add_column('Artist', sa.Column('seeking_venue', sa.Boolean(), nullable=False))
    op.add_column('Venue', sa.Column('genres', sa.ARRAY(sa.String()), nullable=True))
    op.add_column('Venue', sa.Column('seeking_description', sa.String(length=500), nullable=True))
    op.add_column('Venue', sa.Column('seeking_talent', sa.Boolean(), nullable=False))
    op.add_column('shows', sa.Column('artist_id', sa.Integer(), nullable=False))
    op.add_column('shows', sa.Column('venue_id', sa.Integer(), nullable=False))
    op.drop_constraint('shows_venue_show_fkey', 'shows', type_='foreignkey')
    op.drop_constraint('shows_artist_show_fkey', 'shows', type_='foreignkey')
    op.create_foreign_key(None, 'shows', 'Artist', ['artist_id'], ['id'])
    op.create_foreign_key(None, 'shows', 'Venue', ['venue_id'], ['id'])
    op.drop_column('shows', 'artist_show')
    op.drop_column('shows', 'venue_show')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shows', sa.Column('venue_show', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('shows', sa.Column('artist_show', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'shows', type_='foreignkey')
    op.drop_constraint(None, 'shows', type_='foreignkey')
    op.create_foreign_key('shows_artist_show_fkey', 'shows', 'Artist', ['artist_show'], ['id'])
    op.create_foreign_key('shows_venue_show_fkey', 'shows', 'Venue', ['venue_show'], ['id'])
    op.drop_column('shows', 'venue_id')
    op.drop_column('shows', 'artist_id')
    op.drop_column('Venue', 'seeking_talent')
    op.drop_column('Venue', 'seeking_description')
    op.drop_column('Venue', 'genres')
    op.drop_column('Artist', 'seeking_venue')
    op.drop_column('Artist', 'seeking_description')
    # ### end Alembic commands ###
